version: '3.8'

services:
  google-crawler:
    build: ./google-crawler
    container_name: google-crawler
    volumes:
      - ./google-crawler:/app
    command: ["python", "test.py"]
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - selenium-hub

  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59
    container_name: chrome
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge